### ISSUE TITLE
ockam run - a single command to run many ockam “create” commands

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#4479]
To remove the need for typing many commands in an exact order

ockam run - a single command to run many ockam “create” commands where what is created is specified in a declarative file.

This example series of commands becomes:
```
ockam node create telegraf --project project.json --enrollment-token $OCKAM_TELEGRAF_TOKEN
ockam policy set --at telegraf --resource tcp-inlet --expression '(= subject.component "influxdb")'
ockam tcp-inlet create --at /node/telegraf --from 127.0.0.1:8087 --to /project/default/service/forward_to_influxdb/secure/api/service/outlet


ockam node create influxdb --project project.json --enrollment-token $OCKAM_INFLUXDB_TOKEN
ockam policy set --at influxdb --resource tcp-outlet --expression '(= subject.component "telegraf")'
ockam tcp-outlet create --at /node/influxdb --from /service/outlet --to 127.0.0.1:8086
ockam forwarder create influxdb --at /project/default --to /node/influxdb
```

becomes `ockam.yaml`

```yaml
projects:
  default:
    # ...
  
nodes:
  telegraf:
    enrollment-token: $OCKAM_TELEGRAF_TOKEN
    tcp-inlets:
      telegraf:
        from: 127.0.0.1:8087
        to: /project/default/service/forward_to_influxdb/secure/api/service/outlet
        access_control: '(= subject.component "influxdb")'

  influxdb:
    enrollment-token: $OCKAM_INFLUXDB_TOKEN
    tcp-outlets:
      influxdb:
        from: /service/outlet
        to: 127.0.0.1:8086
        access_control: '(= subject.component "telegraf")'
    forwarders:
      influxdb:
        at: /project/default
```

you write that file and then run:

```
$ ockam run
```

We may allow multiple yaml files to be combined - for example project.yml + ockam.yml in some order of presidence.

The YAML may reference the state already in ~/.ockam - for example /project/default or an identity already defined.

Many people don’t like YAML because of its ambiguity so we may ~consider things like cue https://cuelang.org/~ - turns out cue doesn’t have a rust impl yet. TOML and JSON may also be supported as options, but I think the succinctness of YAML has some advantages here.
