### ISSUE TITLE
Fix permission scope in the `ockam-artifacts` workflow

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6177]
# Current behavior

[In the ockam-artifacts workflow](https://github.com/build-trust/ockam/blob/1273a6f413c7c237aecd963db83677a9dc14dd19/.github/workflows/ockam-artifact.yml#L12-L12) we set the `packages: write` permission as a global permission.

# Desired behavior

Instead, we should move this permission to the job scope
```yaml
jobs:
  build_artifact:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
    
```

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>
