### ISSUE TITLE
CI - use rust local action for caching of dependencies in rust check job

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6559]
We recently created a composite action that adds conditional caching of Rust dependencies in this PR https://github.com/build-trust/ockam/pull/6515, we should use this action in place of `Swatinem/rust-cache` in the [rust - check job](https://github.com/build-trust/ockam/blob/e6fc609e327aa9d17dee1296e115a6119c2902a8/.github/workflows/rust.yml#L205-L207) by changing 
```yaml
      - uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43
        with:
          key: "${{ github.job }}-${{ matrix.check_projects }}"
```
to
```yaml
      - uses: ./.github/actions/cache_rust
        with:
          job_name: "${{ github.job }}-${{ matrix.check_projects }}"
```
---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>
