### ISSUE TITLE
CI - use rust local action for caching of dependencies in rust test_ockam_command job

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6560]
We recently created a composite action that adds conditional caching of Rust dependencies in this PR https://github.com/build-trust/ockam/pull/6515, we should use this action in place of `Swatinem/rust-cache` in the [rust - test_ockam_command job](https://github.com/build-trust/ockam/blob/e6fc609e327aa9d17dee1296e115a6119c2902a8/.github/workflows/rust.yml#L243-L245) by changing 
```yaml
      - uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43
        with:
          workspaces: "ockam_cli -> target"
```
to
```yaml
      - uses: ./ockam_bats/.github/actions/cache_rust
        with:
          directory_to_cache: "ockam_cli"
          job_name: ${{ github.job }}
```

---

<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>
